# -*- coding: utf-8 -*-
"""tugas 2_Aldiman Chandra.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/157YeuUPaz9D0D3HU2BSF75TE8D-a_Th5
"""

import numpy as np

a = [1,2,3]
b = [4,5,6]
hasil = a + b
print(sum (hasil))

import numpy as np

nilai_siswa = np.array([85, 55, 40, 90])
print(nilai_siswa[3])

nama = input("Masukkan nama: ")
nim = input("Masukkan NIM: ")

print("hello, world!")
print(f"nama saya {nama}")
print(f"nim saya {nim}")

if 5>2:
  print("Five is greater than two!")

x = 5
y = "jhon"
print(x)
print(y)

x = 4
x = "sally"
print(x)

def getSecond(mylist):
  return(mylist[-1])
getSecond([1,2,3,4,5,6,7,8])

def getSum(mylist):
    sum = 1
    for item in mylist:
       sum /= item
    return sum
getSum([1,2,3,4])

def getSum(mylist):
    sum = 1
    for item in mylist:
       sum *= item
    return sum
getSum([1,2,3,4])

"""Buatlah suatu fungsi untuk
membagi 2 himpunan angka,
jika getSum untuk menjumlahkan angka!
"""

def getSum(himpunan):
    return sum(himpunan)

def divideSets(set1, set2):

    total_set1 = getSum(set1)
    total_set2 = getSum(set2)

    if total_set2 == 0:
        return "Tidak bisa membagi dengan nol"

    return total_set1 / total_set2

himpunan1 = {10, 20, 30}
himpunan2 = {5, 15}

hasil = divideSets(himpunan1, himpunan2)
print(f"Hasil pembagian: {hasil}")

"""Buatlah suatu fungsi untuk :
mengurangi 2 himpunan angka,
jika getSum untuk menjumlahkan angka!

"""

def getSum(angka_set):
    return sum(angka_set)

def subtractSets(set1, set2):
    sum_set1 = getSum(set1)
    sum_set2 = getSum(set2)

    return sum_set1 - sum_set2

set1 = {3, 5, 8}
set2 = {2, 4}

hasil_pengurangan = subtractSets(set1, set2)
print(f"Hasil pengurangan: {hasil_pengurangan}")
